blueprint:
  name: Allumer progressivement les lumières en blanc chaud au coucher du soleil
  description: Allume progressivement les lumières en blanc chaud en fonction du coucher du soleil avec choix de la luminosité maximale.
  domain: automation
  input:
    lights:
      name: Lumières
      description: Liste des lumières à allumer progressivement.
      selector:
        entity:
          domain: light
    duration:
      name: Durée de progression (minutes)
      description: Durée sur laquelle les lumières vont s'allumer progressivement.
      default: 30
      selector:
        number:
          min: 1
          max: 120
          step: 1
    max_brightness:
      name: Luminosité maximale (%)
      description: Luminosité maximale pour les lumières.
      default: 100
      selector:
        number:
          min: 1
          max: 100
          step: 1

trigger:
  platform: sun
  event: sunset
  offset: "-00:30:00"

action:
  - service: light.turn_on
    target:
      entity_id: !input lights
    data_template:
      brightness_pct: "{{ (states.input_number.max_brightness.state | int) * (100 / (states.input_number.duration.state | float)) * (now().timestamp() - state_attr('sun.sun', 'next_setting') | float) / 60 / 100 }}"
      color_temp: 370  # Température de blanc chaud par défaut
