homeassistant:
  enabled: true
  status_topic: homeassistant/status
  experimental_event_entities: true
frontend:
  enabled: true
  port: 8080
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://XXX.XXX.XXX.XXX:1883
  user: z2m_client
  password: XXX
  keepalive: 60
  reject_unauthorized: true
  version: 5
serial:
  port: /dev/ttyUSB0
  adapter: ember
  rtscts: false
advanced:
  log_level: error
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 514
    protocol: udp4
    type: '5424'
  channel: 15
device_options: {}
version: 4
